# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/UrbaniecZelenay.SKS.Package.Services'
    fileType: 'json'
    targetFiles: |
      **/AppSettings.json

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'publish'
  inputs:
    command: 'publish'
    arguments: '/p:IsWebConfigTransformDisabled=true'
    publishWebProjects: true

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: test
    projects: '**/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "XPlat Code Coverage"'
    testRunTitle: TestsResult

- task: reportgenerator@5
  displayName: 'Merge reports into one report to be published'
  inputs:
    reports: '$(Agent.TempDirectory)/**/*.cobertura.xml'
    targetdir: '$(Build.SourcesDirectory)/CoverageResults'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish test coverage report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/CoverageResults/Cobertura.xml'

- task: PublishPipelineArtifact@1
  displayName: 'Publish compiled webapp to release pipeline'
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'CD'
    publishLocation: 'pipeline'