# Default username is "sa"
# Set your password with "SA_PASSWORD"
version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourPassword
    ports: 
      - 1433:1433
    volumes:
      - ~/mssql/data:/var/opt/mssql/data/
  adminer:
    image: knom/adminer-mssql
    ports:
      - 8080:8080
    environment:
       - ADMINER_PLUGINS=tinymce
       - ADMINER_DESIGN=flat
       - ADMINER_DEFAULT_SERVER=sqlserver