/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using UrbaniecZelenay.SKS.Package.BusinessLogic;
using UrbaniecZelenay.SKS.Package.BusinessLogic.Entities.Exceptions;
using UrbaniecZelenay.SKS.Package.BusinessLogic.Interfaces;
using UrbaniecZelenay.SKS.Package.DataAccess.Interfaces;
using UrbaniecZelenay.SKS.Package.DataAccess.Sql;
using UrbaniecZelenay.SKS.Package.Services.Attributes;
using UrbaniecZelenay.SKS.Package.Services.DTOs;
using BlParcel = UrbaniecZelenay.SKS.Package.BusinessLogic.Entities.Parcel;

namespace UrbaniecZelenay.SKS.Package.Services.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class RecipientApiController : ControllerBase
    {
        private readonly IRecipientLogic recipientLogic;
        private readonly IMapper mapper;
        private readonly ILogger<RecipientApiController> logger;

        public RecipientApiController(ILogger<RecipientApiController> logger, IMapper mapper,
            IRecipientLogic recipientLogic)
        {
            this.logger = logger;
            this.recipientLogic = recipientLogic;
            this.mapper = mapper;
        }

        /// <summary>
        /// Find the latest state of a parcel by its tracking ID. 
        /// </summary>
        /// <param name="trackingId">The tracking ID of the parcel. E.g. PYJRB4HZ6 </param>
        /// <response code="200">Parcel exists, here&#x27;s the tracking information.</response>
        /// <response code="400">The operation failed due to an error.</response>
        /// <response code="404">Parcel does not exist with this tracking ID.</response>
        [HttpGet]
        [Route("/parcel/{trackingId}")]
        [ValidateModelState]
        [SwaggerOperation("TrackParcel")]
        [SwaggerResponse(statusCode: 200, type: typeof(TrackingInformation),
            description: "Parcel exists, here&#x27;s the tracking information.")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "The operation failed due to an error.")]
        public virtual IActionResult TrackParcel(
            [FromRoute] [Required] [RegularExpression(@"^[A-Z0-9]{9}$")]
            string trackingId)
        {
            logger.LogInformation($"Track Parcel with ID {trackingId}");
            BlParcel blResult;
            try
            {
                blResult = recipientLogic.TrackParcel(trackingId);
            }
            catch (BlArgumentException ex)
            {
                logger.LogError(ex, "Error occured while tracking parcel.");
                return StatusCode(400, new Error
                {
                    // For security purposes only the last error message in the stack is shown to the end user!
                    ErrorMessage = ex.Message
                });
            }
            catch (BlValidationException ex)
            {
                logger.LogError(ex, "Error occured while tracking parcel.");
                return StatusCode(400, new Error
                {
                    ErrorMessage = ex.Message
                });
            }
            catch (BlDataNotFoundException ex)
            {
                logger.LogError(ex, "Error occured while tracking parcel.");
                return StatusCode(404, new Error
                {
                    ErrorMessage = ex.Message
                });
            }
            catch (BlRepositoryException ex)
            {
                logger.LogError(ex, "Error occured while tracking parcel.");
                return StatusCode(500, new Error
                {
                    ErrorMessage = ex.Message
                });
            }

            var svcResult = mapper.Map<TrackingInformation>(blResult);
            logger.LogDebug($"Mapping Bl/Svc {blResult} => {svcResult}");
            return new ObjectResult(svcResult);
        }
    }
}