/*
 * Parcel Logistics Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using AutoMapper;
using UrbaniecZelenay.SKS.Package.BusinessLogic;
using UrbaniecZelenay.SKS.Package.BusinessLogic.Interfaces;
using UrbaniecZelenay.SKS.Package.DataAccess.Sql;
using UrbaniecZelenay.SKS.Package.Services.Attributes;
using UrbaniecZelenay.SKS.Package.Services.DTOs;

namespace UrbaniecZelenay.SKS.Package.Services.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class StaffApiController : ControllerBase
    {
        private readonly IStaffLogic staffLogic;
        private readonly IMapper mapper;
        
        public StaffApiController(ParcelLogisticsContext context, IMapper mapper)
        {
            this.staffLogic = new StaffLogic(new ParcelRepository(context), mapper);
            this.mapper = mapper;
        }
        
        // public StaffApiController(IMapper mapper, IStaffLogic staffLogic)
        // {
        //     this.staffLogic = staffLogic;
        //     this.mapper = mapper;
        // }
        
        /// <summary>
        /// Report that a Parcel has been delivered at it&#x27;s final destination address. 
        /// </summary>
        /// <param name="trackingId">The tracking ID of the parcel. E.g. PYJRB4HZ6 </param>
        /// <response code="200">Successfully reported hop.</response>
        /// <response code="400">The operation failed due to an error.</response>
        /// <response code="404">Parcel does not exist with this tracking ID. </response>
        [HttpPost]
        [Route("/parcel/{trackingId}/reportDelivery/")]
        [ValidateModelState]
        [SwaggerOperation("ReportParcelDelivery")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "The operation failed due to an error.")]
        public virtual IActionResult ReportParcelDelivery(
            [FromRoute] [Required] [RegularExpression(@"^[A-Z0-9]{9}$")] string trackingId)
        {
            // if (trackingId == null)
            // {
            //     return StatusCode(400, new Error
            //     {
            //         ErrorMessage = "No tracking ID given"
            //     });
            // }
            // //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // // return StatusCode(200);
            //
            // //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // // return StatusCode(400, default(Error));
            //
            // //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // // return StatusCode(404);
            
            try
            {
                staffLogic.ReportParcelDelivery(trackingId);
            }
            catch (ArgumentNullException)
            {
                return StatusCode(400, new Error
                {
                    ErrorMessage = "Invalid Payload"
                });
            }
            // TODO Create NotFoundException
            // catch (NotFoundException)
            // {
            //     return StatusCode(404, new Error
            //     {
            //         ErrorMessage = "Parcel does not exist with this tracking ID or hop with code not found."
            //     });
            // }
            
            return StatusCode(200);
        }

        /// <summary>
        /// Report that a Parcel has arrived at a certain hop either Warehouse or Truck. 
        /// </summary>
        /// <param name="trackingId">The tracking ID of the parcel. E.g. PYJRB4HZ6 </param>
        /// <param name="code">The Code of the hop (Warehouse or Truck).</param>
        /// <response code="200">Successfully reported hop.</response>
        /// <response code="400">The operation failed due to an error.</response>
        /// <response code="404">Parcel does not exist with this tracking ID or hop with code not found. </response>
        [HttpPost]
        [Route("/parcel/{trackingId}/reportHop/{code}")]
        [ValidateModelState]
        [SwaggerOperation("ReportParcelHop")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "The operation failed due to an error.")]
        public virtual IActionResult ReportParcelHop(
            [FromRoute] [Required] [RegularExpression(@"^[A-Z0-9]{9}$")] string trackingId,
            [FromRoute] [Required] [RegularExpression(@"^[A-Z]{4}\d{1,4}$")] string code)
        {
            // if (code == null)
            // {
            //     return StatusCode(400, new Error
            //     {
            //         ErrorMessage = "No code given"
            //     });
            // }
            // //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // // return StatusCode(200);
            //
            // //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // // return StatusCode(400, default(Error));
            //
            // //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // // return StatusCode(404);
            //
            // return StatusCode(200);
            
            try
            {
                staffLogic.ReportParcelHop(trackingId, code);
            }
            catch (ArgumentNullException)
            {
                return StatusCode(400, new Error
                {
                    ErrorMessage = "Invalid Payload"
                });
            }
            // TODO Create NotFoundException
            // catch (NotFoundException)
            // {
            //     return StatusCode(404, new Error
            //     {
            //         ErrorMessage = "Parcel does not exist with this tracking ID or hop with code not found."
            //     });
            // }
            
            return StatusCode(200);
        }
    }
}